name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to PythonAnywhere
      uses: efiShtainer/pythonanywhere-deploy@v1.3
      with:
        pythonanywhere_username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        pythonanywhere_api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        project_path: '/home/justincicd/server'
        project_source_path: '.'
        restart_web_app: true
