name: Restart PythonAnywhere app

on:
  push:
    branches:
      - master

jobs:
  restart-pythonanywhere-app:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Flask app on PythonAnywhere
        run: |
          echo "Restarting PythonAnywhere web app..."
          curl -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
               -X POST \
               https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_DOMAIN }}/reload/
        env:
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
          PYTHONANYWHERE_USERNAME: justincicd
          PYTHONANYWHERE_DOMAIN: justincicd.pythonanywhere.com
